controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev6
      - Rev5
      - Rev7
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev7
initial:  # Define initial robot poses.
  - group: arm
    pose: p1